### ISSUE TITLE
datetime.datetime with zoneinfo.ZoneInfo as tzinfo not working

### ISSUE THREAD

**Issue by rudcode** [psqlpy-python/psqlpy#100]
Using test_value_converter.py with this change will fail the test with excecption psqlpy.exceptions.PyToRustValueMappingError: Can't convert value from python to rust type: Can not convert you datetime to rust type

```
now_datetime_with_tz = datetime.datetime(
    2024,
    4,
    13,
    17,
    3,
    46,
    142574,
    tzinfo=zoneinfo.ZoneInfo(key='Asia/Jakarta'),
)
```

**Comment by chandr-andr** [comment]
Closing the issue because of new release
