### ISSUE TITLE
Does it support vector type from pgvector?

### ISSUE THREAD

**Issue by egorsmkv** [psqlpy-python/psqlpy#101]

**Comment by chandr-andr** [comment]
@egorsmkv Hello! Currently no. I had a quick look at some realizations. It seems isn't difficult.  
I'll add this integrations when I find some free time.

**Comment by egorsmkv** [comment]
Thank you!

**Comment by chandr-andr** [comment]
@egorsmkv Hello! I've made a new release with Vector support.
Please check `PgVector` extra type - https://psqlpy-python.github.io/usage/types/extra_types.html

**Comment by egorsmkv** [comment]
@chandr-andr checked, works fine, thank you for the update!
