### ISSUE TITLE
support for pydantic models

### ISSUE THREAD

**Issue by kesavkolla** [psqlpy-python/psqlpy#104]
Add support for converting QueryResult to pydantic model. I think implementing row factory for pydantic model or even at rust level adding this as dependency crate would be useful.

**Comment by chandr-andr** [comment]
@kesavkolla Hello! Thank you for your issue.
You can use this method to convert to pydantic model.
https://psqlpy-python.github.io/components/results.html#as-class

**Comment by kesavkolla** [comment]
Ok thanks.
