### ISSUE TITLE
How to set schema?

### ISSUE THREAD

**Issue by kesavkolla** [psqlpy-python/psqlpy#105]
I don't see any connection parameter for search_path. This is very useful specially when we have to deal with multiple schemas inside Postgres.

**Comment by chandr-andr** [comment]
Could you please share a example of usage?

**Comment by kesavkolla** [comment]
I found the solution what I was looking for.

Basically `options` is what I need to set.

```
options('-csearch_path=schema1,public,pg_catalog')
```

Once I set this one I could make my queries to work properly.

**Comment by chandr-andr** [comment]
Great, thanks!
