### ISSUE TITLE
docker-compose.yml not found on psqlpy-stress folder

### ISSUE THREAD

**Issue by BimaAdi** [psqlpy-python/psqlpy#61]
If you read the README.md on psqlpy-stess folder [https://github.com/qaspen-python/psqlpy/blob/main/psqlpy-stress/README.md](https://github.com/qaspen-python/psqlpy/blob/main/psqlpy-stress/README.md).  You found that you need to perform `docker compose up` but I don't find any docker-compose.yml file. on psqlpy-stress folder. Is It missing or typo on README.md?

**Comment by chandr-andr** [comment]
Hello! We are changing our benchmarks at the moment. Previously we were using JMeter with influx and grafana for testing and now we've switched to [bombardier](https://github.com/codesenberg/bombardier), but didn't have time to change README.

**Comment by insani7y** [comment]
Hi! We've just update our README on our driver's stress testing. You can check it out [here](https://github.com/qaspen-python/psqlpy/tree/main/psqlpy-stress)
