### ISSUE TITLE
 psqlpy.exceptions.RustToPyValueMappingError: array contains too many dimensions

### ISSUE THREAD

**Issue by nicolaspi** [psqlpy-python/psqlpy#79]
psqlpy-0.7.6
The following code raises: `psqlpy.exceptions.RustToPyValueMappingError: Can't convert value from driver to python type: Cannot convert PostgreSQL type _int4 into Python type, err: array contains too many dimensions`
(the query executes properly in PSQL)

```python
import asyncio
from psqlpy import ConnectionPool


def main():
    db_pool = ConnectionPool()
    result = asyncio.run(db_pool.execute(
        "SELECT array_agg(arr) FROM (SELECT array(SELECT generate_series(0, 10, 1)) as arr FROM (SELECT generate_series(0, 10, 1) as value));",
    ))
    result.result()
    db_pool.close()

main()
```

**Comment by chandr-andr** [comment]
@nicolaspi Hello!
I've made a new release https://github.com/psqlpy-python/psqlpy/releases/tag/0.7.7 with support for multi-dimensional arrays.
Please check it out)
