### ISSUE TITLE
PyJSONB/PyJSON can't handle jsons with nested lists

### ISSUE THREAD

**Issue by vonsteer** [psqlpy-python/psqlpy#82]
psqlpy-v0.7.8
The following code raises: 
`psqlpy.exceptions.PyToRustValueMappingError: Can't convert value from python to rust type: Your value in dict isn't supported by JSON
`
```python
from psqlpy.extra_types import PyJSON

PyJSON({"data": [{"hello":"there"}]})
```

**Comment by chandr-andr** [comment]
Hello!
Thank you very much for your issue. I'm looking into it right now.

**Comment by chandr-andr** [comment]
@vonsteer I've made a new PR with a fix and a better solution. As soon as all check complete, I'm gonna create new release and you can test that problem is fixed.
https://github.com/psqlpy-python/psqlpy/pull/83

**Comment by chandr-andr** [comment]
@vonsteer Please check the new release https://github.com/psqlpy-python/psqlpy/releases/tag/0.7.9

**Comment by vonsteer** [comment]
Just tested, works as desired! Thanks @chandr-andr for the really quick and good fix!
