### ISSUE TITLE
does not handle array types

### ISSUE THREAD

**Issue by SamGrisey** [psqlpy-python/psqlpy#86]
It would seem that array types are not being recognized properly. If I create a simple table:

```
CREATE TABLE IF NOT EXISTS test (
    id serial NOT NULL PRIMARY KEY,
    tags TEXT[]
);
```

then add some rows and do a

```
res = await transaction.fetch("SELECT * FROM test;")
return res.result()
```

the ```return res.result()``` line causes a crash:

```
pyo3_runtime.PanicException: called `Option::unwrap()` on a `None` value
```

The rust code looks like its expecting a postgres type "TEXT ARRAY" but the type is really "text[]". Even if I declare the table column as having type "TEXT ARRAY" instead of "TEXT[]", \d still reports it as "text[]"

EDIT:
It actually works fine with the same simple table on a fresh database, there must be something different with the existing database... but the array column does indeed crash with that error with fetched on the old database, just no idea why now...

**Comment by chandr-andr** [comment]
@SamGrisey Hello! 
Thank you very much for the issue.
I’ll look into it today.

**Comment by SamGrisey** [comment]
Ignore what I said above, the error seems to be with default array values, not my old db instance.
Example SQL:
```
CREATE TABLE IF NOT EXISTS test (
    id serial NOT NULL PRIMARY KEY,
    locked_fields text[] NOT NULL DEFAULT array[]::text[]
);

INSERT INTO test VALUES(1, '{"abc"}');
INSERT INTO test(id) VALUES(2);
```

running ```SELECT * FROM test WHERE id = 1;``` works fine, but running ```SELECT * FROM test WHERE id = 2;``` will cause that crash.

**Comment by chandr-andr** [comment]
@SamGrisey Okay, I know what’s the problem here, I’ll fix it as soon as I come to my laptop

**Comment by chandr-andr** [comment]
@SamGrisey Please check new version - https://github.com/psqlpy-python/psqlpy/releases/tag/0.7.11

**Comment by SamGrisey** [comment]
Yep, it's working now 👍

**Comment by chandr-andr** [comment]
That's great!
I'm closing the issue for now. Don't hesitate to open more if you find any bugs.
