### ISSUE TITLE
Ambiguous SSL error when attempting to connect to database with pem cert

### ISSUE THREAD

**Issue by brizzbuzz** [psqlpy-python/psqlpy#89]
Hello 👋 I'd love to give psqlpy a go for a project I'm working on, but connection to the database must pass along a PEM file.  It doesn't look like you guys support the sslrootcert option for postgres, unless I'm missing something, which is totally possible. 

Thanks!

**Comment by chandr-andr** [comment]
@brizzbuzz Hello! 
We support SSL via ssl_mode and ca_file.

Could you please provide more information about your situation (example, why you need sslrootcert, and anything useful), so I can help you?

**Comment by brizzbuzz** [comment]
Wow fast response! 🚀 I'm probably doing something dumb then.  Here's my example

```py
import os
from typing import Final

from dotenv import load_dotenv
from psqlpy import ConnectionPool, SslMode

load_dotenv()

user = os.getenv("DB_USER")
password = os.getenv("DB_PASSWORD")
host = os.getenv("DB_HOST")
port = os.getenv("DB_PORT")
database = os.getenv("DB_NAME")
ca_file = "/path/to/my/cert.pem"


db_pool: Final = ConnectionPool(
    username=user,
    password=password,
    host=host,
    port=int(port),
    db_name=database,
    ssl_mode=SslMode.VerifyFull,
    ca_file=open(ca_file).read(),
)


async def main() -> None:
    print(f"Usr: {user}")
    print(f"Pwd: {password}")
    print(f"Host: {host}")
    print(f"Port: {port}")
    print(f"DB: {database}")
    print(f"CA: {ca_file}")
    print(f"File Contents: {open(ca_file).read()}")

    connection = await db_pool.connection()
    await connection.execute("SELECT 1")
    print("Connected to database")
    await connection.close()


if __name__ == "__main__":
    import asyncio

    asyncio.run(main())
```

which currently fails 

Traceback (most recent call last):
  File "/home/rbrink/Workspace/ryan-aer/helios/src/database.py", line 17, in <module>
    db_pool: Final = ConnectionPool(
                     ^^^^^^^^^^^^^^^
psqlpy.exceptions.SSLError: Cannot create set SSL: error:80000024:system library:(unknown function):reason(2):crypto/bio/bss_file.c:67:, error:10080002:BIO routines:(unknown function):system lib:crypto/bio/bss_file.c:77:, error:05880020:x509 certificate routines:(unknown function):BIO lib:crypto/x509/by_file.c:231:
error: Recipe `run` failed on line 13 with exit code 1

**Comment by brizzbuzz** [comment]
fwiw, I'm running this on NixOS, so maybe there is an assumed dependency at the OS layer which is not present in my system / is not linked as expected... going to change the title to more accurately reflect the issue

**Comment by chandr-andr** [comment]
Hmm, it looks strange, I've never had any experience with NixOS, so I cannot tell you anything about it.

Anyway, how do you create your cert file? Can you show me an example?

I've tested SSL mode with different servers and conditions and it always works so that we could find a problem.

**Comment by brizzbuzz** [comment]
:/ i figured it out, i think it was two problems

1.  ca_file=open(ca_file).read(), this is wrong, i just needed to feed the file path, not the contents
2. there was some issue with the encoding of the password from the AWS rds command that I was piping in... using boto3 to get the password instead fixed the problem..

So basically... user error haha

Thanks for the speedy replies!

**Comment by chandr-andr** [comment]
@brizzbuzz Oh, normal user mistakes) 
It’s great that everything is good at the end)
