### ISSUE TITLE
Add interval type

### ISSUE THREAD

**Issue by rudcode** [psqlpy-python/psqlpy#94]
Hi, can you add interval type and map it to datetime.timedelta in python?

**Comment by chandr-andr** [comment]
Hello!
Thanks for the issue, I'll add it today.

**Comment by chandr-andr** [comment]
@rudcode Hello! Thanks for waiting, I had many things on weekends.
You can check new version on the library with support for `timedelta` - https://github.com/psqlpy-python/psqlpy/releases/tag/0.8.1

**Comment by rudcode** [comment]
Thank you for resolving this so quickly! I have tested this and it works perfect.
