### ISSUE TITLE
Debug info?

### ISSUE THREAD

**Issue by egorsmkv** [psqlpy-python/psqlpy#98]
I see these prints in console:

```
'str'
'str'
'str'
'int'
'str'
'str'
'str'
'float'
'int'
'str'
'int'
```

Seems like this line produces them:
https://github.com/psqlpy-python/psqlpy/blob/4ff39a79f6b6d53c32d5f0e5f0a2ded1e0582a13/src/value_converter.rs#L749C5-L749C52

**Comment by chandr-andr** [comment]
Hello! Yes, it's my bad.

I made a new version, and in 15-20 mins it will be released.
https://github.com/psqlpy-python/psqlpy/tree/refs/tags/0.8.4

**Comment by egorsmkv** [comment]
Thanks

**Comment by chandr-andr** [comment]
@egorsmkv You can check - https://github.com/psqlpy-python/psqlpy/releases/tag/0.8.4

**Comment by egorsmkv** [comment]
Works correctly, thanks.
